### ISSUE TITLE
🍖 For the meat eaters

### ISSUE THREAD

**Issue by astroash** [yvonne-liu/friendsgiving#2]
![44740209_1110673085757337_1240836418549317632_n](https://user-images.githubusercontent.com/14337958/47997711-1b0d3c00-e0fd-11e8-9556-c2ea480a064c.jpg)

**Comment by Akin909** [comment]
Can't decide if this is the best or worst thing I've ever seen 😶

**Comment by ZooeyMiller** [comment]
closing this issue due to irrelevance and nightmares
